// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: enum.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EyeColor int32

const (
	EyeColor_EYE_COLOR_UNSPECIFIED EyeColor = 0
	EyeColor_EYE_COLOR_GREEN       EyeColor = 1
	EyeColor_EYE_COLOR_BLUE        EyeColor = 2
	EyeColor_EYE_COLOR_BROWN       EyeColor = 3
)

// Enum value maps for EyeColor.
var (
	EyeColor_name = map[int32]string{
		0: "EYE_COLOR_UNSPECIFIED",
		1: "EYE_COLOR_GREEN",
		2: "EYE_COLOR_BLUE",
		3: "EYE_COLOR_BROWN",
	}
	EyeColor_value = map[string]int32{
		"EYE_COLOR_UNSPECIFIED": 0,
		"EYE_COLOR_GREEN":       1,
		"EYE_COLOR_BLUE":        2,
		"EYE_COLOR_BROWN":       3,
	}
)

func (x EyeColor) Enum() *EyeColor {
	p := new(EyeColor)
	*p = x
	return p
}

func (x EyeColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EyeColor) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[0].Descriptor()
}

func (EyeColor) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[0]
}

func (x EyeColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EyeColor.Descriptor instead.
func (EyeColor) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{0}
}

type Eye struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EyeColor EyeColor `protobuf:"varint,1,opt,name=eye_color,json=eyeColor,proto3,enum=cotidie.enum.EyeColor" json:"eye_color,omitempty"`
}

func (x *Eye) Reset() {
	*x = Eye{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Eye) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Eye) ProtoMessage() {}

func (x *Eye) ProtoReflect() protoreflect.Message {
	mi := &file_enum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Eye.ProtoReflect.Descriptor instead.
func (*Eye) Descriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{0}
}

func (x *Eye) GetEyeColor() EyeColor {
	if x != nil {
		return x.EyeColor
	}
	return EyeColor_EYE_COLOR_UNSPECIFIED
}

var File_enum_proto protoreflect.FileDescriptor

var file_enum_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f,
	0x74, 0x69, 0x64, 0x69, 0x65, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x22, 0x3a, 0x0a, 0x03, 0x45, 0x79,
	0x65, 0x12, 0x33, 0x0a, 0x09, 0x65, 0x79, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x74, 0x69, 0x64, 0x69, 0x65, 0x2e, 0x65,
	0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x08, 0x65, 0x79,
	0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x2a, 0x63, 0x0a, 0x08, 0x45, 0x79, 0x65, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a,
	0x0f, 0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x47, 0x52, 0x45, 0x45, 0x4e,
	0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f,
	0x42, 0x4c, 0x55, 0x45, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f,
	0x4c, 0x4f, 0x52, 0x5f, 0x42, 0x52, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x42, 0x3d, 0x5a, 0x3b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x6f, 0x74, 0x69, 0x64, 0x69,
	0x65, 0x2f, 0x53, 0x54, 0x45, 0x41, 0x44, 0x59, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x67, 0x6f,
	0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_enum_proto_rawDescOnce sync.Once
	file_enum_proto_rawDescData = file_enum_proto_rawDesc
)

func file_enum_proto_rawDescGZIP() []byte {
	file_enum_proto_rawDescOnce.Do(func() {
		file_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_proto_rawDescData)
	})
	return file_enum_proto_rawDescData
}

var file_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_enum_proto_goTypes = []interface{}{
	(EyeColor)(0), // 0: cotidie.enum.EyeColor
	(*Eye)(nil),   // 1: cotidie.enum.Eye
}
var file_enum_proto_depIdxs = []int32{
	0, // 0: cotidie.enum.Eye.eye_color:type_name -> cotidie.enum.EyeColor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_enum_proto_init() }
func file_enum_proto_init() {
	if File_enum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_enum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Eye); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_proto_goTypes,
		DependencyIndexes: file_enum_proto_depIdxs,
		EnumInfos:         file_enum_proto_enumTypes,
		MessageInfos:      file_enum_proto_msgTypes,
	}.Build()
	File_enum_proto = out.File
	file_enum_proto_rawDesc = nil
	file_enum_proto_goTypes = nil
	file_enum_proto_depIdxs = nil
}
