// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: optional.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BothServiceClient is the client API for BothService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BothServiceClient interface {
	TestBoth(ctx context.Context, in *BothRequest, opts ...grpc.CallOption) (*BothResponse, error)
}

type bothServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBothServiceClient(cc grpc.ClientConnInterface) BothServiceClient {
	return &bothServiceClient{cc}
}

func (c *bothServiceClient) TestBoth(ctx context.Context, in *BothRequest, opts ...grpc.CallOption) (*BothResponse, error) {
	out := new(BothResponse)
	err := c.cc.Invoke(ctx, "/greet.BothService/TestBoth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BothServiceServer is the server API for BothService service.
// All implementations must embed UnimplementedBothServiceServer
// for forward compatibility
type BothServiceServer interface {
	TestBoth(context.Context, *BothRequest) (*BothResponse, error)
	mustEmbedUnimplementedBothServiceServer()
}

// UnimplementedBothServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBothServiceServer struct {
}

func (UnimplementedBothServiceServer) TestBoth(context.Context, *BothRequest) (*BothResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestBoth not implemented")
}
func (UnimplementedBothServiceServer) mustEmbedUnimplementedBothServiceServer() {}

// UnsafeBothServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BothServiceServer will
// result in compilation errors.
type UnsafeBothServiceServer interface {
	mustEmbedUnimplementedBothServiceServer()
}

func RegisterBothServiceServer(s grpc.ServiceRegistrar, srv BothServiceServer) {
	s.RegisterService(&BothService_ServiceDesc, srv)
}

func _BothService_TestBoth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BothRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BothServiceServer).TestBoth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.BothService/TestBoth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BothServiceServer).TestBoth(ctx, req.(*BothRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BothService_ServiceDesc is the grpc.ServiceDesc for BothService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BothService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet.BothService",
	HandlerType: (*BothServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestBoth",
			Handler:    _BothService_TestBoth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optional.proto",
}
