// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: optional.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KtOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *KtOne) Reset() {
	*x = KtOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_optional_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KtOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KtOne) ProtoMessage() {}

func (x *KtOne) ProtoReflect() protoreflect.Message {
	mi := &file_optional_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KtOne.ProtoReflect.Descriptor instead.
func (*KtOne) Descriptor() ([]byte, []int) {
	return file_optional_proto_rawDescGZIP(), []int{0}
}

func (x *KtOne) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type KtTwo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *KtTwo) Reset() {
	*x = KtTwo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_optional_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KtTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KtTwo) ProtoMessage() {}

func (x *KtTwo) ProtoReflect() protoreflect.Message {
	mi := &file_optional_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KtTwo.ProtoReflect.Descriptor instead.
func (*KtTwo) Descriptor() ([]byte, []int) {
	return file_optional_proto_rawDescGZIP(), []int{1}
}

func (x *KtTwo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type KtBoth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	One *KtOne `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two *KtTwo `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`
}

func (x *KtBoth) Reset() {
	*x = KtBoth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_optional_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KtBoth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KtBoth) ProtoMessage() {}

func (x *KtBoth) ProtoReflect() protoreflect.Message {
	mi := &file_optional_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KtBoth.ProtoReflect.Descriptor instead.
func (*KtBoth) Descriptor() ([]byte, []int) {
	return file_optional_proto_rawDescGZIP(), []int{2}
}

func (x *KtBoth) GetOne() *KtOne {
	if x != nil {
		return x.One
	}
	return nil
}

func (x *KtBoth) GetTwo() *KtTwo {
	if x != nil {
		return x.Two
	}
	return nil
}

type BothRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*KtBoth `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *BothRequest) Reset() {
	*x = BothRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_optional_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BothRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BothRequest) ProtoMessage() {}

func (x *BothRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optional_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BothRequest.ProtoReflect.Descriptor instead.
func (*BothRequest) Descriptor() ([]byte, []int) {
	return file_optional_proto_rawDescGZIP(), []int{3}
}

func (x *BothRequest) GetData() []*KtBoth {
	if x != nil {
		return x.Data
	}
	return nil
}

type BothResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BothResponse) Reset() {
	*x = BothResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_optional_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BothResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BothResponse) ProtoMessage() {}

func (x *BothResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optional_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BothResponse.ProtoReflect.Descriptor instead.
func (*BothResponse) Descriptor() ([]byte, []int) {
	return file_optional_proto_rawDescGZIP(), []int{4}
}

func (x *BothResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_optional_proto protoreflect.FileDescriptor

var file_optional_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x67, 0x72, 0x65, 0x65, 0x74, 0x22, 0x17, 0x0a, 0x05, 0x4b, 0x74, 0x4f, 0x6e, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x1b, 0x0a, 0x05, 0x4b, 0x74, 0x54, 0x77, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a,
	0x06, 0x4b, 0x74, 0x42, 0x6f, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x4b, 0x74, 0x4f,
	0x6e, 0x65, 0x52, 0x03, 0x6f, 0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x03, 0x74, 0x77, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x4b, 0x74, 0x54,
	0x77, 0x6f, 0x52, 0x03, 0x74, 0x77, 0x6f, 0x22, 0x30, 0x0a, 0x0b, 0x42, 0x6f, 0x74, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x4b, 0x74, 0x42,
	0x6f, 0x74, 0x68, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x28, 0x0a, 0x0c, 0x42, 0x6f, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x42, 0x0a, 0x0b, 0x42, 0x6f, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x74, 0x68, 0x12, 0x12,
	0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x42, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x42, 0x6f, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x6f, 0x74, 0x69, 0x64, 0x69, 0x65, 0x2f, 0x53, 0x54,
	0x45, 0x41, 0x44, 0x59, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x42, 0x61, 0x73, 0x69, 0x63, 0x73,
	0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_optional_proto_rawDescOnce sync.Once
	file_optional_proto_rawDescData = file_optional_proto_rawDesc
)

func file_optional_proto_rawDescGZIP() []byte {
	file_optional_proto_rawDescOnce.Do(func() {
		file_optional_proto_rawDescData = protoimpl.X.CompressGZIP(file_optional_proto_rawDescData)
	})
	return file_optional_proto_rawDescData
}

var file_optional_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_optional_proto_goTypes = []interface{}{
	(*KtOne)(nil),        // 0: greet.KtOne
	(*KtTwo)(nil),        // 1: greet.KtTwo
	(*KtBoth)(nil),       // 2: greet.KtBoth
	(*BothRequest)(nil),  // 3: greet.BothRequest
	(*BothResponse)(nil), // 4: greet.BothResponse
}
var file_optional_proto_depIdxs = []int32{
	0, // 0: greet.KtBoth.one:type_name -> greet.KtOne
	1, // 1: greet.KtBoth.two:type_name -> greet.KtTwo
	2, // 2: greet.BothRequest.data:type_name -> greet.KtBoth
	3, // 3: greet.BothService.TestBoth:input_type -> greet.BothRequest
	4, // 4: greet.BothService.TestBoth:output_type -> greet.BothResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_optional_proto_init() }
func file_optional_proto_init() {
	if File_optional_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_optional_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KtOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_optional_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KtTwo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_optional_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KtBoth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_optional_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BothRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_optional_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BothResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_optional_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_optional_proto_goTypes,
		DependencyIndexes: file_optional_proto_depIdxs,
		MessageInfos:      file_optional_proto_msgTypes,
	}.Build()
	File_optional_proto = out.File
	file_optional_proto_rawDesc = nil
	file_optional_proto_goTypes = nil
	file_optional_proto_depIdxs = nil
}
